
[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 10.75

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[terminal]
shell = "fish"
